<?php

namespace Database\Seeders;

use App\Models\Barang\Warna;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class WarnaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Warna::truncate();

        Warna::upsert(
            [
                ['kode' => 'WRN.1', 'nama' => 'PUTIH', 'keterangan' => 'PUTIH'],
                ['kode' => 'WRN.2', 'nama' => 'MUDA', 'keterangan' => 'MUDA'],
                ['kode' => 'WRN.3', 'nama' => 'TUA', 'keterangan' => 'TUA'],
                ['kode' => 'WRN.4', 'nama' => 'SEDANG', 'keterangan' => 'SEDANG'],
                ['kode' => 'WRN.5', 'nama' => 'TUA SPECIAL', 'keterangan' => 'TUA SPECIAL'],
                ['kode' => 'WRN.6', 'nama' => 'MISTY', 'keterangan' => 'MISTY'],
                ['kode' => 'WRN.7', 'nama' => 'TUA SUPER SPECIAL', 'keterangan' => 'TUA SUPER SPECIAL'],
                ['kode' => 'WRN.8', 'nama' => 'ALL COLOR', 'keterangan' => 'ALL COLOR'],
                ['kode' => 'WRN.9', 'nama' => 'TUA SPESIAL', 'keterangan' => 'TUA SPESIAL'],
                ['kode' => 'WRN.10', 'nama' => 'MISTY PUTIH', 'keterangan' => 'MISTY PUTIH'],
                ['kode' => 'WRN.11', 'nama' => 'TUA 3', 'keterangan' => 'TUA 3'],
                ['kode' => 'WRN.12', 'nama' => 'TWOTONE', 'keterangan' => 'TWOTONE'],
                ['kode' => 'WRN.13', 'nama' => 'RAINBOW', 'keterangan' => 'RAINBOW'],
                ['kode' => 'WRN.14', 'nama' => '1  PUTIH', 'keterangan' => '1  PUTIH'],
                ['kode' => 'WRN.15', 'nama' => '2  PINK BABY', 'keterangan' => '2  PINK BABY'],
                ['kode' => 'WRN.16', 'nama' => '3  BIRU BABY', 'keterangan' => '3  BIRU BABY'],
                ['kode' => 'WRN.17', 'nama' => '4  HIJAU TOSCA', 'keterangan' => '4  HIJAU TOSCA'],
                ['kode' => 'WRN.18', 'nama' => '5  CREAM', 'keterangan' => '5  CREAM'],
                ['kode' => 'WRN.19', 'nama' => '6  MAGENTA', 'keterangan' => '6  MAGENTA'],
                ['kode' => 'WRN.20', 'nama' => '7  TURQIS', 'keterangan' => '7  TURQIS'],
                ['kode' => 'WRN.21', 'nama' => '8  HIJAU FUJI', 'keterangan' => '8  HIJAU FUJI'],
                ['kode' => 'WRN.22', 'nama' => '9  KUNING KENARI', 'keterangan' => '9  KUNING KENARI'],
                ['kode' => 'WRN.23', 'nama' => '10  MERAH CABE', 'keterangan' => '10  MERAH CABE'],
                ['kode' => 'WRN.24', 'nama' => '11  BENHUR', 'keterangan' => '11  BENHUR'],
                ['kode' => 'WRN.25', 'nama' => '12  HIJAU ARMY', 'keterangan' => '12  HIJAU ARMY'],
                ['kode' => 'WRN.26', 'nama' => '13  KUNING BUSUK', 'keterangan' => '13  KUNING BUSUK'],
                ['kode' => 'WRN.27', 'nama' => '14  MAROON', 'keterangan' => '14  MAROON'],
                ['kode' => 'WRN.28', 'nama' => '15  DONGKER', 'keterangan' => '15  DONGKER'],
                ['kode' => 'WRN.29', 'nama' => '16  HIJAU BOTOL', 'keterangan' => '16  HIJAU BOTOL'],
                ['kode' => 'WRN.30', 'nama' => '17  ORANGE', 'keterangan' => '17  ORANGE'],
                ['kode' => 'WRN.31', 'nama' => '18  COKLAT ', 'keterangan' => '18  COKLAT '],
                ['kode' => 'WRN.32', 'nama' => '19  COKLAT KOPI', 'keterangan' => '19  COKLAT KOPI'],
                ['kode' => 'WRN.33', 'nama' => '20  HITAM', 'keterangan' => '20  HITAM'],
                ['kode' => 'WRN.34', 'nama' => '21  ABU MUDA', 'keterangan' => '21  ABU MUDA'],
                ['kode' => 'WRN.35', 'nama' => '22  ABU TUA ', 'keterangan' => '22  ABU TUA '],
                ['kode' => 'WRN.36', 'nama' => '23  MISTY MUDA', 'keterangan' => '23  MISTY MUDA'],
                ['kode' => 'WRN.37', 'nama' => '24  MISTY TUA', 'keterangan' => '24  MISTY TUA'],
                ['kode' => 'WRN.38', 'nama' => '25  PUTIH', 'keterangan' => '25  PUTIH'],
                ['kode' => 'WRN.39', 'nama' => '26  PINK BABY', 'keterangan' => '26  PINK BABY'],
                ['kode' => 'WRN.40', 'nama' => '27  BIRU BABY', 'keterangan' => '27  BIRU BABY'],
                ['kode' => 'WRN.41', 'nama' => '28  ORANGE', 'keterangan' => '28  ORANGE'],
                ['kode' => 'WRN.42', 'nama' => '29  LILAC', 'keterangan' => '29  LILAC'],
                ['kode' => 'WRN.43', 'nama' => '30  MERAH CABE', 'keterangan' => '30  MERAH CABE'],
                ['kode' => 'WRN.44', 'nama' => '31  BENHUR', 'keterangan' => '31  BENHUR'],
                ['kode' => 'WRN.45', 'nama' => '32  TOSCA', 'keterangan' => '32  TOSCA'],
                ['kode' => 'WRN.46', 'nama' => '33  MAROON', 'keterangan' => '33  MAROON'],
                ['kode' => 'WRN.47', 'nama' => '34  NAVY', 'keterangan' => '34  NAVY'],
                ['kode' => 'WRN.48', 'nama' => '35  HIJAU FUJI', 'keterangan' => '35  HIJAU FUJI'],
                ['kode' => 'WRN.49', 'nama' => '36  COKLAT MUDA', 'keterangan' => '36  COKLAT MUDA'],
                ['kode' => 'WRN.50', 'nama' => '37  TURQIS', 'keterangan' => '37  TURQIS'],
                ['kode' => 'WRN.51', 'nama' => '38  HIJAU TUA', 'keterangan' => '38  HIJAU TUA'],
                ['kode' => 'WRN.52', 'nama' => '9 ABU TUA', 'keterangan' => '9 ABU TUA'],
                ['kode' => 'WRN.53', 'nama' => '1 PUTIH BLUISH', 'keterangan' => '1 PUTIH BLUISH'],
                ['kode' => 'WRN.54', 'nama' => '2 PUTIH BLUISH-2', 'keterangan' => '2 PUTIH BLUISH-2'],
                ['kode' => 'WRN.55', 'nama' => '3 PUTIH COTINUOUS', 'keterangan' => '3 PUTIH COTINUOUS'],
                ['kode' => 'WRN.56', 'nama' => '4 ABU ASAP', 'keterangan' => '4 ABU ASAP'],
                ['kode' => 'WRN.57', 'nama' => '18 UNGU MUDA', 'keterangan' => '18 UNGU MUDA'],
                ['kode' => 'WRN.58', 'nama' => '22 HIJAU MINT', 'keterangan' => '22 HIJAU MINT'],
                ['kode' => 'WRN.59', 'nama' => '26 PINK', 'keterangan' => '26 PINK'],
                ['kode' => 'WRN.60', 'nama' => '34 COKLAT ABU', 'keterangan' => '34 COKLAT ABU'],
                ['kode' => 'WRN.61', 'nama' => '35 COKLAT SEDANG', 'keterangan' => '35 COKLAT SEDANG'],
                ['kode' => 'WRN.62', 'nama' => '39 KUNING KENARI-1', 'keterangan' => '39 KUNING KENARI-1'],
                ['kode' => 'WRN.63', 'nama' => '41 KUNING KENARI-3', 'keterangan' => '41 KUNING KENARI-3'],
                ['kode' => 'WRN.64', 'nama' => '42 KUNING MAS', 'keterangan' => '42 KUNING MAS'],
                ['kode' => 'WRN.65', 'nama' => '43 KUNING LEMON', 'keterangan' => '43 KUNING LEMON'],
                ['kode' => 'WRN.66', 'nama' => '44 KUNING BUSUK-1', 'keterangan' => '44 KUNING BUSUK-1'],
                ['kode' => 'WRN.67', 'nama' => '49 TOSCA SEDANG-1', 'keterangan' => '49 TOSCA SEDANG-1'],
                ['kode' => 'WRN.68', 'nama' => '52 BIRU SEDANG', 'keterangan' => '52 BIRU SEDANG'],
                ['kode' => 'WRN.69', 'nama' => '55 HIJAU STABILO-3', 'keterangan' => '55 HIJAU STABILO-3'],
                ['kode' => 'WRN.70', 'nama' => '58 BLUE REEF', 'keterangan' => '58 BLUE REEF'],
                ['kode' => 'WRN.71', 'nama' => '60 DUSTY PINK-2', 'keterangan' => '60 DUSTY PINK-2'],
                ['kode' => 'WRN.72', 'nama' => '61 BLUSH PINK', 'keterangan' => '61 BLUSH PINK'],
                ['kode' => 'WRN.73', 'nama' => '65 MINERAL GREEN', 'keterangan' => '65 MINERAL GREEN'],
                ['kode' => 'WRN.74', 'nama' => '92 HITAM REAKTIF-1', 'keterangan' => '92 HITAM REAKTIF-1'],
                ['kode' => 'WRN.75', 'nama' => '93 HITAM REAKTIF-2', 'keterangan' => '93 HITAM REAKTIF-2'],
                ['kode' => 'WRN.76', 'nama' => '95 UNGU TUA-1', 'keterangan' => '95 UNGU TUA-1'],
                ['kode' => 'WRN.77', 'nama' => '97 TURQIS TUA-1', 'keterangan' => '97 TURQIS TUA-1'],
                ['kode' => 'WRN.78', 'nama' => '100 ABU TUA-1', 'keterangan' => '100 ABU TUA-1'],
                ['kode' => 'WRN.79', 'nama' => '102 FANTA-1', 'keterangan' => '102 FANTA-1'],
                ['kode' => 'WRN.80', 'nama' => '103 FANTA-2', 'keterangan' => '103 FANTA-2'],
                ['kode' => 'WRN.81', 'nama' => '104 MERAH CABE-1', 'keterangan' => '104 MERAH CABE-1'],
                ['kode' => 'WRN.82', 'nama' => '107 HIJAU TOSCA-1 ', 'keterangan' => '107 HIJAU TOSCA-1 '],
                ['kode' => 'WRN.83', 'nama' => '109 HIJAU BOTOL-1', 'keterangan' => '109 HIJAU BOTOL-1'],
                ['kode' => 'WRN.84', 'nama' => '110 HIJAU BOTOL-2', 'keterangan' => '110 HIJAU BOTOL-2'],
                ['kode' => 'WRN.85', 'nama' => '112 HIJAU TNI-2', 'keterangan' => '112 HIJAU TNI-2'],
                ['kode' => 'WRN.86', 'nama' => '113 COKLAT KOPI-1', 'keterangan' => '113 COKLAT KOPI-1'],
                ['kode' => 'WRN.87', 'nama' => '114 COKLAT KOPI-2', 'keterangan' => '114 COKLAT KOPI-2'],
                ['kode' => 'WRN.88', 'nama' => '115 KUNING MANGO', 'keterangan' => '115 KUNING MANGO'],
                ['kode' => 'WRN.89', 'nama' => '116 ORANGE', 'keterangan' => '116 ORANGE'],
                ['kode' => 'WRN.90', 'nama' => '117 MAROON-1', 'keterangan' => '117 MAROON-1'],
                ['kode' => 'WRN.91', 'nama' => '121 MERAH HATI', 'keterangan' => '121 MERAH HATI'],
                ['kode' => 'WRN.92', 'nama' => '122 ROYAL BLUE', 'keterangan' => '122 ROYAL BLUE'],
                ['kode' => 'WRN.93', 'nama' => '123 BLUE BLACK', 'keterangan' => '123 BLUE BLACK'],
                ['kode' => 'WRN.94', 'nama' => '125 TOFFEE', 'keterangan' => '125 TOFFEE'],
                ['kode' => 'WRN.95', 'nama' => '137 MERAH SPECIAL', 'keterangan' => '137 MERAH SPECIAL'],
                ['kode' => 'WRN.96', 'nama' => '138 HITAM BALI', 'keterangan' => '138 HITAM BALI'],
                ['kode' => 'WRN.97', 'nama' => '139 HIJAU FUJI-1', 'keterangan' => '139 HIJAU FUJI-1'],
                ['kode' => 'WRN.98', 'nama' => '143 TURQIS SPECIAL', 'keterangan' => '143 TURQIS SPECIAL'],
                ['kode' => 'WRN.99', 'nama' => '44 MISTY M71', 'keterangan' => '44 MISTY M71'],
                ['kode' => 'WRN.100', 'nama' => '45 MISTY M81', 'keterangan' => '45 MISTY M81'],
                ['kode' => 'WRN.101', 'nama' => '39  KUNING BUSUK', 'keterangan' => '39  KUNING BUSUK'],
                ['kode' => 'WRN.102', 'nama' => '40  COKLAT KOPI', 'keterangan' => '40  COKLAT KOPI'],
                ['kode' => 'WRN.103', 'nama' => '41  HITAM', 'keterangan' => '41  HITAM'],
                ['kode' => 'WRN.104', 'nama' => '42  HIJAU ARMY', 'keterangan' => '42  HIJAU ARMY'],
                ['kode' => 'WRN.105', 'nama' => '43  ABU MUDA', 'keterangan' => '43  ABU MUDA'],
                ['kode' => 'WRN.106', 'nama' => '1 HITAM BALI', 'keterangan' => '1 HITAM BALI'],
                ['kode' => 'WRN.107', 'nama' => '2 NAVY', 'keterangan' => '2 NAVY'],
                ['kode' => 'WRN.108', 'nama' => '3 HIJAU BOTOL', 'keterangan' => '3 HIJAU BOTOL'],
                ['kode' => 'WRN.109', 'nama' => '4 MISTYY 71 PUTIH', 'keterangan' => '4 MISTYY 71 PUTIH'],
                ['kode' => 'WRN.110', 'nama' => '5 KUNING BUSUK', 'keterangan' => '5 KUNING BUSUK'],
                ['kode' => 'WRN.111', 'nama' => '6 PUTIH BLUISH', 'keterangan' => '6 PUTIH BLUISH'],
                ['kode' => 'WRN.112', 'nama' => '2 MERAH SPECIAL', 'keterangan' => '2 MERAH SPECIAL'],
                ['kode' => 'WRN.113', 'nama' => '3 HITAM BALI', 'keterangan' => '3 HITAM BALI'],
                ['kode' => 'WRN.114', 'nama' => '4 HIJAU BOTOL', 'keterangan' => '4 HIJAU BOTOL'],
                ['kode' => 'WRN.115', 'nama' => '6 MAROON', 'keterangan' => '6 MAROON'],
                ['kode' => 'WRN.116', 'nama' => '7 NAVY', 'keterangan' => '7 NAVY'],
                ['kode' => 'WRN.117', 'nama' => '8 HIJAU TNI', 'keterangan' => '8 HIJAU TNI'],
                ['kode' => 'WRN.118', 'nama' => '3 PUTIH CONTINUOUS', 'keterangan' => '3 PUTIH CONTINUOUS'],
                ['kode' => 'WRN.119', 'nama' => '7 BROKEN WHITE-1', 'keterangan' => '7 BROKEN WHITE-1'],
                ['kode' => 'WRN.120', 'nama' => '19 ORANGE MUDA', 'keterangan' => '19 ORANGE MUDA'],
                ['kode' => 'WRN.121', 'nama' => '21 TURQIS MUDA', 'keterangan' => '21 TURQIS MUDA'],
                ['kode' => 'WRN.122', 'nama' => '23 HIJAU MUDA', 'keterangan' => '23 HIJAU MUDA'],
                ['kode' => 'WRN.123', 'nama' => '25 SALEM MUDA', 'keterangan' => '25 SALEM MUDA'],
                ['kode' => 'WRN.124', 'nama' => '30 SALEM-1', 'keterangan' => '30 SALEM-1'],
                ['kode' => 'WRN.125', 'nama' => '37 ABU SEDANG-1', 'keterangan' => '37 ABU SEDANG-1'],
                ['kode' => 'WRN.126', 'nama' => '46 KUNING KUNYIT', 'keterangan' => '46 KUNING KUNYIT'],
                ['kode' => 'WRN.127', 'nama' => '47 BIRU SEDANG', 'keterangan' => '47 BIRU SEDANG'],
                ['kode' => 'WRN.128', 'nama' => '50 TOSCA SEDANG-2', 'keterangan' => '50 TOSCA SEDANG-2'],
                ['kode' => 'WRN.129', 'nama' => '51 TURQIS SEDANG', 'keterangan' => '51 TURQIS SEDANG'],
                ['kode' => 'WRN.130', 'nama' => '53 HIJAU STABILO-1', 'keterangan' => '53 HIJAU STABILO-1'],
                ['kode' => 'WRN.131', 'nama' => '57 CORAL RED', 'keterangan' => '57 CORAL RED'],
                ['kode' => 'WRN.132', 'nama' => '59 DUSTY PINK-1', 'keterangan' => '59 DUSTY PINK-1'],
                ['kode' => 'WRN.133', 'nama' => '62 BUBBLEGUM PINK', 'keterangan' => '62 BUBBLEGUM PINK'],
                ['kode' => 'WRN.134', 'nama' => '63 DUSTY MAGENTA', 'keterangan' => '63 DUSTY MAGENTA'],
                ['kode' => 'WRN.135', 'nama' => '64 BIRU MARINIR', 'keterangan' => '64 BIRU MARINIR'],
                ['kode' => 'WRN.136', 'nama' => '66 DUSTY GREEN', 'keterangan' => '66 DUSTY GREEN'],
                ['kode' => 'WRN.137', 'nama' => '67 PINE GREEN', 'keterangan' => '67 PINE GREEN'],
                ['kode' => 'WRN.138', 'nama' => '88 HIJAU WARDAH', 'keterangan' => '88 HIJAU WARDAH'],
                ['kode' => 'WRN.139', 'nama' => '91 BRONZE MIST', 'keterangan' => '91 BRONZE MIST'],
                ['kode' => 'WRN.140', 'nama' => '99 TURQIS TUA-3', 'keterangan' => '99 TURQIS TUA-3'],
                ['kode' => 'WRN.141', 'nama' => '108 HIJAU TOSCA-2', 'keterangan' => '108 HIJAU TOSCA-2'],
                ['kode' => 'WRN.142', 'nama' => '119 MAROON-3', 'keterangan' => '119 MAROON-3'],
                ['kode' => 'WRN.143', 'nama' => '120 MAROON-4', 'keterangan' => '120 MAROON-4'],
                ['kode' => 'WRN.144', 'nama' => '127 CELESTIAL BLUE', 'keterangan' => '127 CELESTIAL BLUE'],
                ['kode' => 'WRN.145', 'nama' => '141 BENHUR-1', 'keterangan' => '141 BENHUR-1'],
                ['kode' => 'WRN.146', 'nama' => '5 ABU MUDA', 'keterangan' => '5 ABU MUDA'],
                ['kode' => 'WRN.147', 'nama' => '8 BROKEN WHITE-2', 'keterangan' => '8 BROKEN WHITE-2'],
                ['kode' => 'WRN.148', 'nama' => '9 BIRU MUDA-1', 'keterangan' => '9 BIRU MUDA-1'],
                ['kode' => 'WRN.149', 'nama' => '10 BIRU MUDA-2', 'keterangan' => '10 BIRU MUDA-2'],
                ['kode' => 'WRN.150', 'nama' => '11 BIRU MUDA-3', 'keterangan' => '11 BIRU MUDA-3'],
                ['kode' => 'WRN.151', 'nama' => '12  CREAM', 'keterangan' => '12  CREAM'],
                ['kode' => 'WRN.152', 'nama' => '13 COKLAT SUSU', 'keterangan' => '13 COKLAT SUSU'],
                ['kode' => 'WRN.153', 'nama' => '14 COKLAT MUDA', 'keterangan' => '14 COKLAT MUDA'],
                ['kode' => 'WRN.154', 'nama' => '16 KUNING MUDA-1', 'keterangan' => '16 KUNING MUDA-1'],
                ['kode' => 'WRN.155', 'nama' => '17 KUNING MUDA-2', 'keterangan' => '17 KUNING MUDA-2'],
                ['kode' => 'WRN.156', 'nama' => '20 TOSCA MUDA', 'keterangan' => '20 TOSCA MUDA'],
                ['kode' => 'WRN.157', 'nama' => '27 ROSE MUDA', 'keterangan' => '27 ROSE MUDA'],
                ['kode' => 'WRN.158', 'nama' => '31 SALEM-2', 'keterangan' => '31 SALEM-2'],
                ['kode' => 'WRN.159', 'nama' => '32 UNGU SEDANG', 'keterangan' => '32 UNGU SEDANG'],
                ['kode' => 'WRN.160', 'nama' => '38 ABU SEDANG-2', 'keterangan' => '38 ABU SEDANG-2'],
                ['kode' => 'WRN.161', 'nama' => '40 KUNING KENARI-2', 'keterangan' => '40 KUNING KENARI-2'],
                ['kode' => 'WRN.162', 'nama' => '45 KUNING BUSUK-2', 'keterangan' => '45 KUNING BUSUK-2'],
                ['kode' => 'WRN.163', 'nama' => '54 HIJAU STABILO-2', 'keterangan' => '54 HIJAU STABILO-2'],
                ['kode' => 'WRN.164', 'nama' => '69 PEANUT LATTE', 'keterangan' => '69 PEANUT LATTE'],
                ['kode' => 'WRN.165', 'nama' => '70 PECCAN MOCCA', 'keterangan' => '70 PECCAN MOCCA'],
                ['kode' => 'WRN.166', 'nama' => '73 RUSTY', 'keterangan' => '73 RUSTY'],
                ['kode' => 'WRN.167', 'nama' => '85 HIJAU SEMPURNA', 'keterangan' => '85 HIJAU SEMPURNA'],
                ['kode' => 'WRN.168', 'nama' => '86 HIJAU PUCUK', 'keterangan' => '86 HIJAU PUCUK'],
                ['kode' => 'WRN.169', 'nama' => '87 HIJAU ALPUKAT', 'keterangan' => '87 HIJAU ALPUKAT'],
                ['kode' => 'WRN.170', 'nama' => '94 MERAH BATA', 'keterangan' => '94 MERAH BATA'],
                ['kode' => 'WRN.171', 'nama' => '96 UNGU TUA-2', 'keterangan' => '96 UNGU TUA-2'],
                ['kode' => 'WRN.172', 'nama' => '98 TURQIS TUA-2', 'keterangan' => '98 TURQIS TUA-2'],
                ['kode' => 'WRN.173', 'nama' => '101 ABU TUA-2', 'keterangan' => '101 ABU TUA-2'],
                ['kode' => 'WRN.174', 'nama' => '105 COKLAT SUSU', 'keterangan' => '105 COKLAT SUSU'],
                ['kode' => 'WRN.175', 'nama' => '106 GREEN TOSCA', 'keterangan' => '106 GREEN TOSCA'],
                ['kode' => 'WRN.176', 'nama' => '111 HIJAU TNI-1', 'keterangan' => '111 HIJAU TNI-1'],
                ['kode' => 'WRN.177', 'nama' => '118 MAROON-2', 'keterangan' => '118 MAROON-2'],
                ['kode' => 'WRN.178', 'nama' => '124 CINNAMON BROWN', 'keterangan' => '124 CINNAMON BROWN'],
                ['kode' => 'WRN.179', 'nama' => '126 GINGER TEA', 'keterangan' => '126 GINGER TEA'],
                ['kode' => 'WRN.180', 'nama' => '130 DARK MUSTARD', 'keterangan' => '130 DARK MUSTARD'],
                ['kode' => 'WRN.181', 'nama' => '132 NAVY', 'keterangan' => '132 NAVY'],
                ['kode' => 'WRN.182', 'nama' => '133 OLD NAVY', 'keterangan' => '133 OLD NAVY'],
                ['kode' => 'WRN.183', 'nama' => '140 HIJAU FUJI-2', 'keterangan' => '140 HIJAU FUJI-2'],
                ['kode' => 'WRN.184', 'nama' => '142 BENHUR-2', 'keterangan' => '142 BENHUR-2'],
                ['kode' => 'WRN.185', 'nama' => '6 ABU  BIRU', 'keterangan' => '6 ABU  BIRU'],
                ['kode' => 'WRN.186', 'nama' => '12 CREAM', 'keterangan' => '12 CREAM'],
                ['kode' => 'WRN.187', 'nama' => '15 SAFARI BROWN', 'keterangan' => '15 SAFARI BROWN'],
                ['kode' => 'WRN.188', 'nama' => '24 PEACH MUDA', 'keterangan' => '24 PEACH MUDA'],
                ['kode' => 'WRN.189', 'nama' => '28 FAIRY PINK', 'keterangan' => '28 FAIRY PINK'],
                ['kode' => 'WRN.190', 'nama' => '29 SEA PINK', 'keterangan' => '29 SEA PINK'],
                ['kode' => 'WRN.191', 'nama' => '33 DUSTY VIOLET', 'keterangan' => '33 DUSTY VIOLET'],
                ['kode' => 'WRN.192', 'nama' => '36 BEAVER BROWN', 'keterangan' => '36 BEAVER BROWN'],
                ['kode' => 'WRN.193', 'nama' => '48 BIRU TEAL', 'keterangan' => '48 BIRU TEAL'],
                ['kode' => 'WRN.194', 'nama' => '56 HIJAU TKD', 'keterangan' => '56 HIJAU TKD'],
                ['kode' => 'WRN.195', 'nama' => '68 ATLANTIS GREEN', 'keterangan' => '68 ATLANTIS GREEN'],
                ['kode' => 'WRN.196', 'nama' => '71 SMOKE BLUE', 'keterangan' => '71 SMOKE BLUE'],
                ['kode' => 'WRN.197', 'nama' => '72 TERRA COTTA', 'keterangan' => '72 TERRA COTTA'],
                ['kode' => 'WRN.198', 'nama' => '74 CAMEO BLUE', 'keterangan' => '74 CAMEO BLUE'],
                ['kode' => 'WRN.199', 'nama' => '75 DUSTY PEACH', 'keterangan' => '75 DUSTY PEACH'],
                ['kode' => 'WRN.200', 'nama' => '76 NOSTALGIA ROSE', 'keterangan' => '76 NOSTALGIA ROSE'],
                ['kode' => 'WRN.201', 'nama' => '77 CLOUD BLUE', 'keterangan' => '77 CLOUD BLUE'],
                ['kode' => 'WRN.202', 'nama' => '78 OPULENCE GREEN', 'keterangan' => '78 OPULENCE GREEN'],
                ['kode' => 'WRN.203', 'nama' => '79 LAVENDER LILAC', 'keterangan' => '79 LAVENDER LILAC'],
                ['kode' => 'WRN.204', 'nama' => '80 ASPEN GREEN', 'keterangan' => '80 ASPEN GREEN'],
                ['kode' => 'WRN.205', 'nama' => '81 OCEAN  BLUE', 'keterangan' => '81 OCEAN  BLUE'],
                ['kode' => 'WRN.206', 'nama' => '82 STORM BLUE', 'keterangan' => '82 STORM BLUE'],
                ['kode' => 'WRN.207', 'nama' => '83 AUTUMN GREEN', 'keterangan' => '83 AUTUMN GREEN'],
                ['kode' => 'WRN.208', 'nama' => '84 STORM GREEN', 'keterangan' => '84 STORM GREEN'],
                ['kode' => 'WRN.209', 'nama' => '89 NIAGARA BLUE', 'keterangan' => '89 NIAGARA BLUE'],
                ['kode' => 'WRN.210', 'nama' => '90 VETIVER GRAY', 'keterangan' => '90 VETIVER GRAY'],
                ['kode' => 'WRN.211', 'nama' => '115 COKLAT KOPI-1', 'keterangan' => '115 COKLAT KOPI-1'],
                ['kode' => 'WRN.212', 'nama' => '116 KUNING MANGO', 'keterangan' => '116 KUNING MANGO'],
                ['kode' => 'WRN.213', 'nama' => '180 MAROON-4', 'keterangan' => '180 MAROON-4'],
                ['kode' => 'WRN.214', 'nama' => '128 BURGUNDY', 'keterangan' => '128 BURGUNDY'],
                ['kode' => 'WRN.215', 'nama' => '129 PLUM RED', 'keterangan' => '129 PLUM RED'],
                ['kode' => 'WRN.216', 'nama' => '131 ORANGE BATA', 'keterangan' => '131 ORANGE BATA'],
                ['kode' => 'WRN.217', 'nama' => '134 DARK TOSCA', 'keterangan' => '134 DARK TOSCA'],
                ['kode' => 'WRN.218', 'nama' => '135 CLASSIC BLUE', 'keterangan' => '135 CLASSIC BLUE'],
                ['kode' => 'WRN.219', 'nama' => '136 RED WINE', 'keterangan' => '136 RED WINE'],
                ['kode' => 'WRN.220', 'nama' => 'TURQIS SPECIAL', 'keterangan' => 'TURQIS SPECIAL'],
                ['kode' => 'WRN.221', 'nama' => '144 HITAM MARBLE', 'keterangan' => '144 HITAM MARBLE'],
                ['kode' => 'WRN.222', 'nama' => 'COKLAT PNS', 'keterangan' => 'COKLAT PNS'],
                ['kode' => 'WRN.223', 'nama' => 'HITAM', 'keterangan' => 'HITAM'],
                ['kode' => 'WRN.224', 'nama' => '1 SKY BLUE', 'keterangan' => '1 SKY BLUE'],
                ['kode' => 'WRN.225', 'nama' => '2 FANTA', 'keterangan' => '2 FANTA'],
                ['kode' => 'WRN.226', 'nama' => '3 PUTIH', 'keterangan' => '3 PUTIH'],
                ['kode' => 'WRN.227', 'nama' => '4 HIJAU STABILLO', 'keterangan' => '4 HIJAU STABILLO'],
                ['kode' => 'WRN.228', 'nama' => '5 ORANGE STABILLO', 'keterangan' => '5 ORANGE STABILLO'],
                ['kode' => 'WRN.229', 'nama' => '6 KUNING', 'keterangan' => '6 KUNING'],
                ['kode' => 'WRN.230', 'nama' => '7 ABU', 'keterangan' => '7 ABU'],
                ['kode' => 'WRN.231', 'nama' => '8 MERAH', 'keterangan' => '8 MERAH'],
                ['kode' => 'WRN.232', 'nama' => '9 NAVY', 'keterangan' => '9 NAVY'],
                ['kode' => 'WRN.233', 'nama' => '10 HITAM', 'keterangan' => '10 HITAM'],
                ['kode' => 'WRN.234', 'nama' => '11 HIJAU TNI', 'keterangan' => '11 HIJAU TNI'],
                ['kode' => 'WRN.235', 'nama' => 'ABU MUDA', 'keterangan' => 'ABU MUDA'],
                ['kode' => 'WRN.236', 'nama' => '4  TOSCA', 'keterangan' => '4  TOSCA'],
                ['kode' => 'WRN.237', 'nama' => '7  DEEP BLUE', 'keterangan' => '7  DEEP BLUE'],
                ['kode' => 'WRN.238', 'nama' => '11  TURQIS', 'keterangan' => '11  TURQIS'],
                ['kode' => 'WRN.239', 'nama' => '15  BENHUR', 'keterangan' => '15  BENHUR'],
                ['kode' => 'WRN.240', 'nama' => '18  COKLAT KOPI', 'keterangan' => '18  COKLAT KOPI'],
                ['kode' => 'WRN.241', 'nama' => '19  DONGKER', 'keterangan' => '19  DONGKER'],
                ['kode' => 'WRN.242', 'nama' => '21  VIOLET', 'keterangan' => '21  VIOLET'],
                ['kode' => 'WRN.243', 'nama' => '22  LILAC', 'keterangan' => '22  LILAC'],
                ['kode' => 'WRN.244', 'nama' => '23  ABU MUDA', 'keterangan' => '23  ABU MUDA'],
                ['kode' => 'WRN.245', 'nama' => '24  ABU TUA ', 'keterangan' => '24  ABU TUA '],
                ['kode' => 'WRN.246', 'nama' => '25  MISTY 71', 'keterangan' => '25  MISTY 71'],
                ['kode' => 'WRN.247', 'nama' => '26  MISTY TUA', 'keterangan' => '26  MISTY TUA'],
                ['kode' => 'WRN.248', 'nama' => '27  PUTIH BLUISH', 'keterangan' => '27  PUTIH BLUISH'],
                ['kode' => 'WRN.249', 'nama' => '28  CREAM', 'keterangan' => '28  CREAM'],
                ['kode' => 'WRN.250', 'nama' => '29  KUNING MAS', 'keterangan' => '29  KUNING MAS'],
                ['kode' => 'WRN.251', 'nama' => '30  HIJAU BOTOL', 'keterangan' => '30  HIJAU BOTOL'],
                ['kode' => 'WRN.252', 'nama' => '31  MAROON', 'keterangan' => '31  MAROON'],
                ['kode' => 'WRN.253', 'nama' => '32  NAVY', 'keterangan' => '32  NAVY'],
                ['kode' => 'WRN.254', 'nama' => '33  MISTY 71', 'keterangan' => '33  MISTY 71'],
                ['kode' => 'WRN.255', 'nama' => '34  PUTIH BLUISH', 'keterangan' => '34  PUTIH BLUISH'],
                ['kode' => 'WRN.256', 'nama' => '35  HITAM BALI', 'keterangan' => '35  HITAM BALI'],
                ['kode' => 'WRN.257', 'nama' => '36  HIJAU BOTOL', 'keterangan' => '36  HIJAU BOTOL'],
                ['kode' => 'WRN.258', 'nama' => '37  KUNING BUSUK', 'keterangan' => '37  KUNING BUSUK'],
                ['kode' => 'WRN.259', 'nama' => '38  MAROON', 'keterangan' => '38  MAROON'],
                ['kode' => 'WRN.260', 'nama' => '39  NAVY', 'keterangan' => '39  NAVY'],
                ['kode' => 'WRN.261', 'nama' => '40  BLUE REEF', 'keterangan' => '40  BLUE REEF'],
                ['kode' => 'WRN.262', 'nama' => '41  DUSTY PINK', 'keterangan' => '41  DUSTY PINK'],
                ['kode' => 'WRN.263', 'nama' => '42  TERRA COTTA', 'keterangan' => '42  TERRA COTTA'],
                ['kode' => 'WRN.264', 'nama' => '43  MISTY 71 PUTIH', 'keterangan' => '43  MISTY 71 PUTIH'],
                ['kode' => 'WRN.265', 'nama' => '147 MISTY 71 PUTIH', 'keterangan' => '147 MISTY 71 PUTIH'],
                ['kode' => 'WRN.266', 'nama' => '148 MISTY 81', 'keterangan' => '148 MISTY 81'],
                ['kode' => 'WRN.267', 'nama' => '149 MISTY 61 PUTIH', 'keterangan' => '149 MISTY 61 PUTIH'],
                ['kode' => 'WRN.268', 'nama' => '1 PUTIH', 'keterangan' => '1 PUTIH'],
                ['kode' => 'WRN.269', 'nama' => '2 MISTY 71 PUTIH', 'keterangan' => '2 MISTY 71 PUTIH'],
                ['kode' => 'WRN.270', 'nama' => '3 KUNING KENARI', 'keterangan' => '3 KUNING KENARI'],
                ['kode' => 'WRN.271', 'nama' => '4 ORANGE', 'keterangan' => '4 ORANGE'],
                ['kode' => 'WRN.272', 'nama' => '5 HIJAU STABILO', 'keterangan' => '5 HIJAU STABILO'],
                ['kode' => 'WRN.273', 'nama' => '6 HIJAU FUJI', 'keterangan' => '6 HIJAU FUJI'],
                ['kode' => 'WRN.274', 'nama' => '7 HIJAU TOSCA', 'keterangan' => '7 HIJAU TOSCA'],
                ['kode' => 'WRN.275', 'nama' => '8 FANTA', 'keterangan' => '8 FANTA'],
                ['kode' => 'WRN.276', 'nama' => '9 MERAH CABE', 'keterangan' => '9 MERAH CABE'],
                ['kode' => 'WRN.277', 'nama' => '10 BIRU MUDA', 'keterangan' => '10 BIRU MUDA'],
                ['kode' => 'WRN.278', 'nama' => '11 TURQIS 1 ', 'keterangan' => '11 TURQIS 1 '],
                ['kode' => 'WRN.279', 'nama' => '12 TURQIS 2', 'keterangan' => '12 TURQIS 2'],
                ['kode' => 'WRN.280', 'nama' => '13 BENHUR', 'keterangan' => '13 BENHUR'],
                ['kode' => 'WRN.281', 'nama' => '14 ABU TUA ', 'keterangan' => '14 ABU TUA '],
                ['kode' => 'WRN.282', 'nama' => '15 COKLAT KOPI', 'keterangan' => '15 COKLAT KOPI'],
                ['kode' => 'WRN.283', 'nama' => '16 NAVY', 'keterangan' => '16 NAVY'],
                ['kode' => 'WRN.284', 'nama' => '17 HITAM', 'keterangan' => '17 HITAM'],
                ['kode' => 'WRN.285', 'nama' => '18 ABU SEDANG', 'keterangan' => '18 ABU SEDANG'],
                ['kode' => 'WRN.286', 'nama' => '19 KUNING MAS', 'keterangan' => '19 KUNING MAS'],
                ['kode' => 'WRN.287', 'nama' => '20 HIJAU BOTOL', 'keterangan' => '20 HIJAU BOTOL'],
                ['kode' => 'WRN.288', 'nama' => '21 HITAM TWOTONE', 'keterangan' => '21 HITAM TWOTONE'],
                ['kode' => 'WRN.289', 'nama' => '22 MAROON', 'keterangan' => '22 MAROON'],
                ['kode' => 'WRN.290', 'nama' => '23 MAROON TWO TONE', 'keterangan' => '23 MAROON TWO TONE'],
                ['kode' => 'WRN.291', 'nama' => '24 BENHUR TWOTONE', 'keterangan' => '24 BENHUR TWOTONE'],
                ['kode' => 'WRN.292', 'nama' => '25 HIJAU PUCUK', 'keterangan' => '25 HIJAU PUCUK'],
                ['kode' => 'WRN.293', 'nama' => '26 BIRU SEDANG', 'keterangan' => '26 BIRU SEDANG'],
                ['kode' => 'WRN.294', 'nama' => '27 BIRU MUDA', 'keterangan' => '27 BIRU MUDA'],
                ['kode' => 'WRN.295', 'nama' => '28 CREAM', 'keterangan' => '28 CREAM'],
                ['kode' => 'WRN.296', 'nama' => '29 TOSCA', 'keterangan' => '29 TOSCA'],
                ['kode' => 'WRN.297', 'nama' => '30 TURQIS TUA', 'keterangan' => '30 TURQIS TUA'],
                ['kode' => 'WRN.298', 'nama' => '31 ABU MUDA', 'keterangan' => '31 ABU MUDA'],
                ['kode' => 'WRN.299', 'nama' => '32 HIJAU TUA', 'keterangan' => '32 HIJAU TUA'],
                ['kode' => 'WRN.300', 'nama' => '33 BENHUR', 'keterangan' => '33 BENHUR'],
                ['kode' => 'WRN.301', 'nama' => '34 KUNING BUSUK', 'keterangan' => '34 KUNING BUSUK'],
                ['kode' => 'WRN.302', 'nama' => '35 KUNING TELUR', 'keterangan' => '35 KUNING TELUR'],
                ['kode' => 'WRN.303', 'nama' => '36 MAGENTA', 'keterangan' => '36 MAGENTA'],
                ['kode' => 'WRN.304', 'nama' => '37 DONGKER', 'keterangan' => '37 DONGKER'],
                ['kode' => 'WRN.305', 'nama' => '38 COKLAT', 'keterangan' => '38 COKLAT'],
                ['kode' => 'WRN.306', 'nama' => '39 ORANGE', 'keterangan' => '39 ORANGE'],
                ['kode' => 'WRN.307', 'nama' => '40 MERAH CABE', 'keterangan' => '40 MERAH CABE'],
                ['kode' => 'WRN.308', 'nama' => '41 MAROON', 'keterangan' => '41 MAROON'],
                ['kode' => 'WRN.309', 'nama' => '42 HITAM', 'keterangan' => '42 HITAM'],
                ['kode' => 'WRN.310', 'nama' => '43 MISTY TUA', 'keterangan' => '43 MISTY TUA'],
                ['kode' => 'WRN.311', 'nama' => '44 MISTY MUDA', 'keterangan' => '44 MISTY MUDA'],
                ['kode' => 'WRN.312', 'nama' => '2  KUNING GOLKAR', 'keterangan' => '2  KUNING GOLKAR'],
                ['kode' => 'WRN.313', 'nama' => '3  ABU TUA ', 'keterangan' => '3  ABU TUA '],
                ['kode' => 'WRN.314', 'nama' => '4  MERAH CABE', 'keterangan' => '4  MERAH CABE'],
                ['kode' => 'WRN.315', 'nama' => '5  MAROON ', 'keterangan' => '5  MAROON '],
                ['kode' => 'WRN.316', 'nama' => '6  BENHUR ', 'keterangan' => '6  BENHUR '],
                ['kode' => 'WRN.317', 'nama' => '7  HIJAU BOTOL', 'keterangan' => '7  HIJAU BOTOL'],
                ['kode' => 'WRN.318', 'nama' => '8  DONGKER', 'keterangan' => '8  DONGKER'],
                ['kode' => 'WRN.319', 'nama' => '9  HITAM ', 'keterangan' => '9  HITAM '],
                ['kode' => 'WRN.320', 'nama' => '10  MISTY 71', 'keterangan' => '10  MISTY 71'],
                ['kode' => 'WRN.321', 'nama' => '11  MISTY 71 PUTIH', 'keterangan' => '11  MISTY 71 PUTIH'],
                ['kode' => 'WRN.322', 'nama' => '224 HITAM', 'keterangan' => '224 HITAM'],
                ['kode' => 'WRN.323', 'nama' => '224 KUNING BUSUK', 'keterangan' => '224 KUNING BUSUK'],
                ['kode' => 'WRN.324', 'nama' => '224 MISTY 71 PUTIH', 'keterangan' => '224 MISTY 71 PUTIH'],
                ['kode' => 'WRN.325', 'nama' => '224 MERAH', 'keterangan' => '224 MERAH'],
                ['kode' => 'WRN.326', 'nama' => '224 MAROON', 'keterangan' => '224 MAROON'],
                ['kode' => 'WRN.327', 'nama' => '224 NAVY', 'keterangan' => '224 NAVY'],
                ['kode' => 'WRN.328', 'nama' => '224 PUTIH', 'keterangan' => '224 PUTIH'],
                ['kode' => 'WRN.329', 'nama' => '224 HIJAU TOSCA', 'keterangan' => '224 HIJAU TOSCA'],
                ['kode' => 'WRN.330', 'nama' => '224 ABU TUA', 'keterangan' => '224 ABU TUA'],
                ['kode' => 'WRN.331', 'nama' => '224 ABU MUDA', 'keterangan' => '224 ABU MUDA'],
                ['kode' => 'WRN.332', 'nama' => '224 HIJAU BOTOL', 'keterangan' => '224 HIJAU BOTOL'],
                ['kode' => 'WRN.333', 'nama' => '1  ABU MUDA X PUTIH', 'keterangan' => '1  ABU MUDA X PUTIH'],
                ['kode' => 'WRN.334', 'nama' => '2  ABU TUA X PUTIH ', 'keterangan' => '2  ABU TUA X PUTIH '],
                ['kode' => 'WRN.335', 'nama' => '3  HITAM X PUTIH ', 'keterangan' => '3  HITAM X PUTIH '],
                ['kode' => 'WRN.336', 'nama' => '4  TURQIS X PUTIH ', 'keterangan' => '4  TURQIS X PUTIH '],
                ['kode' => 'WRN.337', 'nama' => '5  NAVY X PUTIH ', 'keterangan' => '5  NAVY X PUTIH '],
                ['kode' => 'WRN.338', 'nama' => '6  BIRU X HITAM', 'keterangan' => '6  BIRU X HITAM'],
                ['kode' => 'WRN.339', 'nama' => '7  MERAH X PUTIH', 'keterangan' => '7  MERAH X PUTIH'],
                ['kode' => 'WRN.340', 'nama' => '8  MAROON X PUTIH', 'keterangan' => '8  MAROON X PUTIH'],
                ['kode' => 'WRN.341', 'nama' => '9  MERAH X HITAM', 'keterangan' => '9  MERAH X HITAM'],
                ['kode' => 'WRN.342', 'nama' => '10  FUJI X PUTIH', 'keterangan' => '10  FUJI X PUTIH'],
                ['kode' => 'WRN.343', 'nama' => '11  TOSCA X NAVY', 'keterangan' => '11  TOSCA X NAVY'],
                ['kode' => 'WRN.344', 'nama' => '12  COKLAT X COKLAT TUA', 'keterangan' => '12  COKLAT X COKLAT TUA'],
                ['kode' => 'WRN.345', 'nama' => '13  NAVY X TURQUIS', 'keterangan' => '13  NAVY X TURQUIS'],
                ['kode' => 'WRN.346', 'nama' => '14  MUSTARD X PUTIH', 'keterangan' => '14  MUSTARD X PUTIH'],
                ['kode' => 'WRN.347', 'nama' => '15  COKLAT X PUTIH', 'keterangan' => '15  COKLAT X PUTIH'],
                ['kode' => 'WRN.348', 'nama' => '16  TOSCA X PUTIH', 'keterangan' => '16  TOSCA X PUTIH'],
                ['kode' => 'WRN.349', 'nama' => '17  INDIGO X PUTIH', 'keterangan' => '17  INDIGO X PUTIH'],
                ['kode' => 'WRN.350', 'nama' => '18  HIJAU X PUTIH', 'keterangan' => '18  HIJAU X PUTIH'],
                ['kode' => 'WRN.351', 'nama' => '19  PUTIH X PINK', 'keterangan' => '19  PUTIH X PINK'],
                ['kode' => 'WRN.352', 'nama' => '20  MOCCA X PUTIH ', 'keterangan' => '20  MOCCA X PUTIH '],
                ['kode' => 'WRN.353', 'nama' => '21  BLACK X TERRACOTTA', 'keterangan' => '21  BLACK X TERRACOTTA'],
                ['kode' => 'WRN.354', 'nama' => '22  BLUE REEF X PUTIH', 'keterangan' => '22  BLUE REEF X PUTIH'],
                ['kode' => 'WRN.355', 'nama' => '23  DUSTY GREEN X PUTIH ', 'keterangan' => '23  DUSTY GREEN X PUTIH '],
                ['kode' => 'WRN.356', 'nama' => '24  MINERAL GREEN X PUTIH ', 'keterangan' => '24  MINERAL GREEN X PUTIH '],
                ['kode' => 'WRN.357', 'nama' => '25  BLUSH PINK X PUTIH', 'keterangan' => '25  BLUSH PINK X PUTIH'],
                ['kode' => 'WRN.358', 'nama' => '26  LAVENDER LILAC X PUTIH', 'keterangan' => '26  LAVENDER LILAC X PUTIH'],
                ['kode' => 'WRN.359', 'nama' => '27  BIRU MARINIR X PUTIH', 'keterangan' => '27  BIRU MARINIR X PUTIH'],
                ['kode' => 'WRN.360', 'nama' => '28  CELESTIAL BLUE X PUTIH ', 'keterangan' => '28  CELESTIAL BLUE X PUTIH '],
                ['kode' => 'WRN.361', 'nama' => '2  KUNING KENARI', 'keterangan' => '2  KUNING KENARI'],
                ['kode' => 'WRN.362', 'nama' => '3  KUNING KUNYIT', 'keterangan' => '3  KUNING KUNYIT'],
                ['kode' => 'WRN.363', 'nama' => '4  MUSTARD', 'keterangan' => '4  MUSTARD'],
                ['kode' => 'WRN.364', 'nama' => '5  DARK FUSCHIA', 'keterangan' => '5  DARK FUSCHIA'],
                ['kode' => 'WRN.365', 'nama' => '6  MERAH HATI', 'keterangan' => '6  MERAH HATI'],
                ['kode' => 'WRN.366', 'nama' => '7  BURGUNDY', 'keterangan' => '7  BURGUNDY'],
                ['kode' => 'WRN.367', 'nama' => '8  GRASS GREEN', 'keterangan' => '8  GRASS GREEN'],
                ['kode' => 'WRN.368', 'nama' => '9  HIJAU ARMY', 'keterangan' => '9  HIJAU ARMY'],
                ['kode' => 'WRN.369', 'nama' => '10  HIJAU BOTOL', 'keterangan' => '10  HIJAU BOTOL'],
                ['kode' => 'WRN.370', 'nama' => '11  TURQUIS TUA', 'keterangan' => '11  TURQUIS TUA'],
                ['kode' => 'WRN.371', 'nama' => '12  NAVY', 'keterangan' => '12  NAVY'],
                ['kode' => 'WRN.372', 'nama' => '13  HITAM', 'keterangan' => '13  HITAM'],
                ['kode' => 'WRN.373', 'nama' => 'PUTIH 145', 'keterangan' => 'PUTIH 145'],
                ['kode' => 'WRN.374', 'nama' => 'ROSE 19', 'keterangan' => 'ROSE 19'],
                ['kode' => 'WRN.375', 'nama' => 'KUNING MUDA 4', 'keterangan' => 'KUNING MUDA 4'],
                ['kode' => 'WRN.376', 'nama' => 'MELON 123', 'keterangan' => 'MELON 123'],
                ['kode' => 'WRN.377', 'nama' => 'BIRU BABY 83', 'keterangan' => 'BIRU BABY 83'],
                ['kode' => 'WRN.378', 'nama' => 'CREAM 9', 'keterangan' => 'CREAM 9'],
                ['kode' => 'WRN.379', 'nama' => 'ROSE 21', 'keterangan' => 'ROSE 21'],
                ['kode' => 'WRN.380', 'nama' => 'KENARI 158', 'keterangan' => 'KENARI 158'],
                ['kode' => 'WRN.381', 'nama' => 'STABILO 139', 'keterangan' => 'STABILO 139'],
                ['kode' => 'WRN.382', 'nama' => 'BIRU 2', 'keterangan' => 'BIRU 2'],
                ['kode' => 'WRN.383', 'nama' => 'CREAM 10', 'keterangan' => 'CREAM 10'],
                ['kode' => 'WRN.384', 'nama' => 'PINK 3', 'keterangan' => 'PINK 3'],
                ['kode' => 'WRN.385', 'nama' => 'KUNING MAS 7', 'keterangan' => 'KUNING MAS 7'],
                ['kode' => 'WRN.386', 'nama' => 'STABILO 138', 'keterangan' => 'STABILO 138'],
                ['kode' => 'WRN.387', 'nama' => 'TURQIS 114', 'keterangan' => 'TURQIS 114'],
                ['kode' => 'WRN.388', 'nama' => 'COKSU 43', 'keterangan' => 'COKSU 43'],
                ['kode' => 'WRN.389', 'nama' => 'FANTA 23', 'keterangan' => 'FANTA 23'],
                ['kode' => 'WRN.390', 'nama' => 'KUBUS 13', 'keterangan' => 'KUBUS 13'],
                ['kode' => 'WRN.391', 'nama' => 'FUJI 62', 'keterangan' => 'FUJI 62'],
                ['kode' => 'WRN.392', 'nama' => 'BIRU SEDANG 157', 'keterangan' => 'BIRU SEDANG 157'],
                ['kode' => 'WRN.393', 'nama' => 'COKLAT KOPI 54', 'keterangan' => 'COKLAT KOPI 54'],
                ['kode' => 'WRN.394', 'nama' => 'MERAH CABE 40', 'keterangan' => 'MERAH CABE 40'],
                ['kode' => 'WRN.395', 'nama' => 'SALEM 28', 'keterangan' => 'SALEM 28'],
                ['kode' => 'WRN.396', 'nama' => 'FUJI 529', 'keterangan' => 'FUJI 529'],
                ['kode' => 'WRN.397', 'nama' => 'TURQIS 110', 'keterangan' => 'TURQIS 110'],
                ['kode' => 'WRN.398', 'nama' => 'KOPI TUTUNG 56', 'keterangan' => 'KOPI TUTUNG 56'],
                ['kode' => 'WRN.399', 'nama' => 'MERAH HATI 30', 'keterangan' => 'MERAH HATI 30'],
                ['kode' => 'WRN.400', 'nama' => 'ORANGE 48', 'keterangan' => 'ORANGE 48'],
                ['kode' => 'WRN.401', 'nama' => 'HIJAU SUPER 125', 'keterangan' => 'HIJAU SUPER 125'],
                ['kode' => 'WRN.402', 'nama' => 'BENHUR 86', 'keterangan' => 'BENHUR 86'],
                ['kode' => 'WRN.403', 'nama' => 'ABU SEDANG 75', 'keterangan' => 'ABU SEDANG 75'],
                ['kode' => 'WRN.404', 'nama' => 'MERAH HATI 32', 'keterangan' => 'MERAH HATI 32'],
                ['kode' => 'WRN.405', 'nama' => 'UNGU MUDA 58', 'keterangan' => 'UNGU MUDA 58'],
                ['kode' => 'WRN.406', 'nama' => 'TOSCA 118', 'keterangan' => 'TOSCA 118'],
                ['kode' => 'WRN.407', 'nama' => 'BENHUR 102', 'keterangan' => 'BENHUR 102'],
                ['kode' => 'WRN.408', 'nama' => 'ABU POLISI 627', 'keterangan' => 'ABU POLISI 627'],
                ['kode' => 'WRN.409', 'nama' => 'HITAM 360', 'keterangan' => 'HITAM 360'],
                ['kode' => 'WRN.410', 'nama' => 'UNGU TUA 302', 'keterangan' => 'UNGU TUA 302'],
                ['kode' => 'WRN.411', 'nama' => 'HIJAU TNI 143', 'keterangan' => 'HIJAU TNI 143'],
                ['kode' => 'WRN.412', 'nama' => 'NAVY 96', 'keterangan' => 'NAVY 96'],
                ['kode' => 'WRN.413', 'nama' => '2  BROKEN WHITE', 'keterangan' => '2  BROKEN WHITE'],
                ['kode' => 'WRN.414', 'nama' => '3  CREAM', 'keterangan' => '3  CREAM'],
                ['kode' => 'WRN.415', 'nama' => '4  COKSU', 'keterangan' => '4  COKSU'],
                ['kode' => 'WRN.416', 'nama' => '5  COKLAT PEMDA ', 'keterangan' => '5  COKLAT PEMDA '],
                ['kode' => 'WRN.417', 'nama' => '6  COKLAT MILO', 'keterangan' => '6  COKLAT MILO'],
                ['kode' => 'WRN.418', 'nama' => '7  MOCCA', 'keterangan' => '7  MOCCA'],
                ['kode' => 'WRN.419', 'nama' => '8  KOPI MUDA', 'keterangan' => '8  KOPI MUDA'],
                ['kode' => 'WRN.420', 'nama' => '9  PINK', 'keterangan' => '9  PINK'],
                ['kode' => 'WRN.421', 'nama' => '10  DARMA WANITA', 'keterangan' => '10  DARMA WANITA'],
                ['kode' => 'WRN.422', 'nama' => '11  ROSE SEDANG', 'keterangan' => '11  ROSE SEDANG'],
                ['kode' => 'WRN.423', 'nama' => '12  FANTA', 'keterangan' => '12  FANTA'],
                ['kode' => 'WRN.424', 'nama' => '13  MERAH CABE', 'keterangan' => '13  MERAH CABE'],
                ['kode' => 'WRN.425', 'nama' => '14  MERAH DARAH', 'keterangan' => '14  MERAH DARAH'],
                ['kode' => 'WRN.426', 'nama' => '15  MERAH HATI', 'keterangan' => '15  MERAH HATI'],
                ['kode' => 'WRN.427', 'nama' => '16  KOPI TUTUNG', 'keterangan' => '16  KOPI TUTUNG'],
                ['kode' => 'WRN.428', 'nama' => '17  KUNING BUSUK', 'keterangan' => '17  KUNING BUSUK'],
                ['kode' => 'WRN.429', 'nama' => '18  ORANGE', 'keterangan' => '18  ORANGE'],
                ['kode' => 'WRN.430', 'nama' => '19  BATA MUDA', 'keterangan' => '19  BATA MUDA'],
                ['kode' => 'WRN.431', 'nama' => '20  SALEM MUDA', 'keterangan' => '20  SALEM MUDA'],
                ['kode' => 'WRN.432', 'nama' => '21  SALEM TUA', 'keterangan' => '21  SALEM TUA'],
                ['kode' => 'WRN.433', 'nama' => '22  MERAH BATA', 'keterangan' => '22  MERAH BATA'],
                ['kode' => 'WRN.434', 'nama' => '24  ABU TUA', 'keterangan' => '24  ABU TUA'],
                ['kode' => 'WRN.435', 'nama' => '25  BIRU BABY', 'keterangan' => '25  BIRU BABY'],
                ['kode' => 'WRN.436', 'nama' => '26  TURQIS', 'keterangan' => '26  TURQIS'],
                ['kode' => 'WRN.437', 'nama' => '27  TOSCA MUDA', 'keterangan' => '27  TOSCA MUDA'],
                ['kode' => 'WRN.438', 'nama' => '28  TOSCA WARDAH', 'keterangan' => '28  TOSCA WARDAH'],
                ['kode' => 'WRN.439', 'nama' => '29  TOSCA SEDANG', 'keterangan' => '29  TOSCA SEDANG'],
                ['kode' => 'WRN.440', 'nama' => '30  TOSCA TUA', 'keterangan' => '30  TOSCA TUA'],
                ['kode' => 'WRN.441', 'nama' => '31  HIJAU BOTOL', 'keterangan' => '31  HIJAU BOTOL'],
                ['kode' => 'WRN.442', 'nama' => '32  BIRU ITB', 'keterangan' => '32  BIRU ITB'],
                ['kode' => 'WRN.443', 'nama' => '33  LAVENDER', 'keterangan' => '33  LAVENDER'],
                ['kode' => 'WRN.444', 'nama' => '34  FUSHIA', 'keterangan' => '34  FUSHIA'],
                ['kode' => 'WRN.445', 'nama' => '35  UNGU MUDA', 'keterangan' => '35  UNGU MUDA'],
                ['kode' => 'WRN.446', 'nama' => '36  UNGU TUA', 'keterangan' => '36  UNGU TUA'],
                ['kode' => 'WRN.447', 'nama' => '37  HIJAU HANSIP', 'keterangan' => '37  HIJAU HANSIP'],
                ['kode' => 'WRN.448', 'nama' => '38  HIJAU PANDAN', 'keterangan' => '38  HIJAU PANDAN'],
                ['kode' => 'WRN.449', 'nama' => '39  HIJAU PUPUS', 'keterangan' => '39  HIJAU PUPUS'],
                ['kode' => 'WRN.450', 'nama' => '40  HIJAU TNI', 'keterangan' => '40  HIJAU TNI'],
                ['kode' => 'WRN.451', 'nama' => '41  BENHUR', 'keterangan' => '41  BENHUR'],
                ['kode' => 'WRN.452', 'nama' => '42  NAVY', 'keterangan' => '42  NAVY'],
                ['kode' => 'WRN.453', 'nama' => '43  HITAM', 'keterangan' => '43  HITAM'],
                ['kode' => 'WRN.454', 'nama' => '44  HIJAU PUCUK', 'keterangan' => '44  HIJAU PUCUK'],
                ['kode' => 'WRN.455', 'nama' => '45  KUNING LEMON ', 'keterangan' => '45  KUNING LEMON '],
                ['kode' => 'WRN.456', 'nama' => '2  ABU MUDA', 'keterangan' => '2  ABU MUDA'],
                ['kode' => 'WRN.457', 'nama' => '3  BIRU ROYAL', 'keterangan' => '3  BIRU ROYAL'],
                ['kode' => 'WRN.458', 'nama' => '4  BLUE BLACK', 'keterangan' => '4  BLUE BLACK'],
                ['kode' => 'WRN.459', 'nama' => '5  KUNING', 'keterangan' => '5  KUNING'],
                ['kode' => 'WRN.460', 'nama' => '6  MERAH', 'keterangan' => '6  MERAH'],
                ['kode' => 'WRN.461', 'nama' => '7  ORANGE', 'keterangan' => '7  ORANGE'],
                ['kode' => 'WRN.462', 'nama' => '8  HIJAU', 'keterangan' => '8  HIJAU'],
                ['kode' => 'WRN.463', 'nama' => '9  HIJAU FUJI', 'keterangan' => '9  HIJAU FUJI'],
                ['kode' => 'WRN.464', 'nama' => '10  BIRU  TUA', 'keterangan' => '10  BIRU  TUA'],
                ['kode' => 'WRN.465', 'nama' => '11  MAGENTA', 'keterangan' => '11  MAGENTA'],
                ['kode' => 'WRN.466', 'nama' => '12  KHAKY', 'keterangan' => '12  KHAKY'],
                ['kode' => 'WRN.467', 'nama' => '16  PUTIH', 'keterangan' => '16  PUTIH'],
                ['kode' => 'WRN.468', 'nama' => '17  HIJAU FUJI', 'keterangan' => '17  HIJAU FUJI'],
                ['kode' => 'WRN.469', 'nama' => '18  HIJAU TOSCA', 'keterangan' => '18  HIJAU TOSCA'],
                ['kode' => 'WRN.470', 'nama' => '19  HIJAU LUMUT', 'keterangan' => '19  HIJAU LUMUT'],
                ['kode' => 'WRN.471', 'nama' => '20  TURQIS', 'keterangan' => '20  TURQIS'],
                ['kode' => 'WRN.472', 'nama' => '21  UNGU TUA', 'keterangan' => '21  UNGU TUA'],
                ['kode' => 'WRN.473', 'nama' => '22  ABU SEDANG', 'keterangan' => '22  ABU SEDANG'],
                ['kode' => 'WRN.474', 'nama' => '23  ABU TUA', 'keterangan' => '23  ABU TUA'],
                ['kode' => 'WRN.475', 'nama' => '24  BENHUR', 'keterangan' => '24  BENHUR'],
                ['kode' => 'WRN.476', 'nama' => '25  NAVY', 'keterangan' => '25  NAVY'],
                ['kode' => 'WRN.477', 'nama' => '26  KUNING', 'keterangan' => '26  KUNING'],
                ['kode' => 'WRN.478', 'nama' => '27  MERAH', 'keterangan' => '27  MERAH'],
                ['kode' => 'WRN.479', 'nama' => '28  MAROON', 'keterangan' => '28  MAROON'],
                ['kode' => 'WRN.480', 'nama' => '29  ORANGE', 'keterangan' => '29  ORANGE'],
                ['kode' => 'WRN.481', 'nama' => '30  HITAM ', 'keterangan' => '30  HITAM '],
                ['kode' => 'WRN.482', 'nama' => '3  BIRU LANGIT', 'keterangan' => '3  BIRU LANGIT'],
                ['kode' => 'WRN.483', 'nama' => '4  COKLAT SUSU', 'keterangan' => '4  COKLAT SUSU'],
                ['kode' => 'WRN.484', 'nama' => '5  DUSTY PINK', 'keterangan' => '5  DUSTY PINK'],
                ['kode' => 'WRN.485', 'nama' => '6  ABU MUDA', 'keterangan' => '6  ABU MUDA'],
                ['kode' => 'WRN.486', 'nama' => '7  UNGU MUDA', 'keterangan' => '7  UNGU MUDA'],
                ['kode' => 'WRN.487', 'nama' => '8  KUNING KENARI', 'keterangan' => '8  KUNING KENARI'],
                ['kode' => 'WRN.488', 'nama' => '9  COKLAT MILO', 'keterangan' => '9  COKLAT MILO'],
                ['kode' => 'WRN.489', 'nama' => '10  FANTA', 'keterangan' => '10  FANTA'],
                ['kode' => 'WRN.490', 'nama' => '11  MERAH CABE', 'keterangan' => '11  MERAH CABE'],
                ['kode' => 'WRN.491', 'nama' => '12  MERAH HATI', 'keterangan' => '12  MERAH HATI'],
                ['kode' => 'WRN.492', 'nama' => '13  MAROON', 'keterangan' => '13  MAROON'],
                ['kode' => 'WRN.493', 'nama' => '14  TOSCA', 'keterangan' => '14  TOSCA'],
                ['kode' => 'WRN.494', 'nama' => '15  HIJAU FUJI', 'keterangan' => '15  HIJAU FUJI'],
                ['kode' => 'WRN.495', 'nama' => '16  HIJAU TNI', 'keterangan' => '16  HIJAU TNI'],
                ['kode' => 'WRN.496', 'nama' => '17  HIJAU BOTOL', 'keterangan' => '17  HIJAU BOTOL'],
                ['kode' => 'WRN.497', 'nama' => '18  KUNING BUSUK', 'keterangan' => '18  KUNING BUSUK'],
                ['kode' => 'WRN.498', 'nama' => '19  ORANGE TUA', 'keterangan' => '19  ORANGE TUA'],
                ['kode' => 'WRN.499', 'nama' => '20  COKLAT KOPI', 'keterangan' => '20  COKLAT KOPI'],
                ['kode' => 'WRN.500', 'nama' => '21  BENHUR', 'keterangan' => '21  BENHUR'],
                ['kode' => 'WRN.501', 'nama' => '22  ABU SMA', 'keterangan' => '22  ABU SMA'],
                ['kode' => 'WRN.502', 'nama' => '24  NAVY', 'keterangan' => '24  NAVY'],
                ['kode' => 'WRN.503', 'nama' => '25  HITAM', 'keterangan' => '25  HITAM'],
                ['kode' => 'WRN.504', 'nama' => '1  PUTIH ', 'keterangan' => '1  PUTIH '],
                ['kode' => 'WRN.505', 'nama' => '2  KUNING MAS ', 'keterangan' => '2  KUNING MAS '],
                ['kode' => 'WRN.506', 'nama' => '3  KUNING KENARI ', 'keterangan' => '3  KUNING KENARI '],
                ['kode' => 'WRN.507', 'nama' => '4  ORANGE ', 'keterangan' => '4  ORANGE '],
                ['kode' => 'WRN.508', 'nama' => '5  PINK ', 'keterangan' => '5  PINK '],
                ['kode' => 'WRN.509', 'nama' => '6  MERAH CABE ', 'keterangan' => '6  MERAH CABE '],
                ['kode' => 'WRN.510', 'nama' => '7  MERAH HATI ', 'keterangan' => '7  MERAH HATI '],
                ['kode' => 'WRN.511', 'nama' => '8  TOSCA ', 'keterangan' => '8  TOSCA '],
                ['kode' => 'WRN.512', 'nama' => '9  HIJAU STABILO ', 'keterangan' => '9  HIJAU STABILO '],
                ['kode' => 'WRN.513', 'nama' => '10  HIJAU FUJI ', 'keterangan' => '10  HIJAU FUJI '],
                ['kode' => 'WRN.514', 'nama' => '11  HIJAU FUJI ', 'keterangan' => '11  HIJAU FUJI '],
                ['kode' => 'WRN.515', 'nama' => '12  HIJAU SUPER ', 'keterangan' => '12  HIJAU SUPER '],
                ['kode' => 'WRN.516', 'nama' => '13  HIJAU TNI', 'keterangan' => '13  HIJAU TNI'],
                ['kode' => 'WRN.517', 'nama' => '14  UNGU TUA ', 'keterangan' => '14  UNGU TUA '],
                ['kode' => 'WRN.518', 'nama' => '15  BIRU BABY ', 'keterangan' => '15  BIRU BABY '],
                ['kode' => 'WRN.519', 'nama' => '16  BIRU SDG ', 'keterangan' => '16  BIRU SDG '],
                ['kode' => 'WRN.520', 'nama' => '17  TURQIS ', 'keterangan' => '17  TURQIS '],
                ['kode' => 'WRN.521', 'nama' => '18  BENHUR ', 'keterangan' => '18  BENHUR '],
                ['kode' => 'WRN.522', 'nama' => '19  BENHUR ', 'keterangan' => '19  BENHUR '],
                ['kode' => 'WRN.523', 'nama' => '20  NAVY ', 'keterangan' => '20  NAVY '],
                ['kode' => 'WRN.524', 'nama' => '21  HITAM ', 'keterangan' => '21  HITAM '],
                ['kode' => 'WRN.525', 'nama' => '22  ABU SEDANG ', 'keterangan' => '22  ABU SEDANG '],
                ['kode' => 'WRN.526', 'nama' => '23  COKLAT KOPI', 'keterangan' => '23  COKLAT KOPI'],
                ['kode' => 'WRN.527', 'nama' => '24  COKLAT TUTUNG ', 'keterangan' => '24  COKLAT TUTUNG '],
                ['kode' => 'WRN.528', 'nama' => '25  FANTA ', 'keterangan' => '25  FANTA '],
                ['kode' => 'WRN.529', 'nama' => '26  FANTA UTAMA ', 'keterangan' => '26  FANTA UTAMA '],
                ['kode' => 'WRN.530', 'nama' => '1 TOI TOI', 'keterangan' => '1 TOI TOI'],
                ['kode' => 'WRN.531', 'nama' => '2 ARMANI', 'keterangan' => '2 ARMANI'],
                ['kode' => 'WRN.532', 'nama' => '3 PLACID BLUE', 'keterangan' => '3 PLACID BLUE'],
                ['kode' => 'WRN.533', 'nama' => '4 CHATEAU PINK', 'keterangan' => '4 CHATEAU PINK'],
                ['kode' => 'WRN.534', 'nama' => '5 FORMULA ONE', 'keterangan' => '5 FORMULA ONE'],
                ['kode' => 'WRN.535', 'nama' => '6 ORANGE.COM', 'keterangan' => '6 ORANGE.COM'],
                ['kode' => 'WRN.536', 'nama' => '7 KALAMATA', 'keterangan' => '7 KALAMATA'],
                ['kode' => 'WRN.537', 'nama' => '8 GHOTIC GRAPE', 'keterangan' => '8 GHOTIC GRAPE'],
                ['kode' => 'WRN.538', 'nama' => '9 INK', 'keterangan' => '9 INK'],
                ['kode' => 'WRN.539', 'nama' => '10 GREY MARL', 'keterangan' => '10 GREY MARL'],
                ['kode' => 'WRN.540', 'nama' => '11 BLUE NIGHT', 'keterangan' => '11 BLUE NIGHT'],
                ['kode' => 'WRN.541', 'nama' => '12 BARBERRY', 'keterangan' => '12 BARBERRY'],
                ['kode' => 'WRN.542', 'nama' => '13 RIFLE GREEN', 'keterangan' => '13 RIFLE GREEN'],
                ['kode' => 'WRN.543', 'nama' => '14 CHARCHOAL MARL', 'keterangan' => '14 CHARCHOAL MARL'],
                ['kode' => 'WRN.544', 'nama' => 'L. GREEN', 'keterangan' => 'L. GREEN'],
                ['kode' => 'WRN.545', 'nama' => 'PINK CANDY', 'keterangan' => 'PINK CANDY'],
                ['kode' => 'WRN.546', 'nama' => 'P. ORANGE', 'keterangan' => 'P. ORANGE'],
                ['kode' => 'WRN.547', 'nama' => 'K. KENARI', 'keterangan' => 'K. KENARI'],
                ['kode' => 'WRN.548', 'nama' => 'H. DAUN', 'keterangan' => 'H. DAUN'],
                ['kode' => 'WRN.549', 'nama' => 'H. TNI', 'keterangan' => 'H. TNI'],
                ['kode' => 'WRN.550', 'nama' => 'H. TOSCA', 'keterangan' => 'H. TOSCA'],
                ['kode' => 'WRN.551', 'nama' => 'HJ FUJI', 'keterangan' => 'HJ FUJI'],
                ['kode' => 'WRN.552', 'nama' => 'BIRU MUDA', 'keterangan' => 'BIRU MUDA'],
                ['kode' => 'WRN.553', 'nama' => 'R. BLUE', 'keterangan' => 'R. BLUE'],
                ['kode' => 'WRN.554', 'nama' => 'NAVY', 'keterangan' => 'NAVY'],
                ['kode' => 'WRN.555', 'nama' => 'TURQUIS', 'keterangan' => 'TURQUIS'],
                ['kode' => 'WRN.556', 'nama' => 'ABU TUA', 'keterangan' => 'ABU TUA'],
                ['kode' => 'WRN.557', 'nama' => 'DK PINK', 'keterangan' => 'DK PINK'],
                ['kode' => 'WRN.558', 'nama' => 'K. EMAS', 'keterangan' => 'K. EMAS'],
                ['kode' => 'WRN.559', 'nama' => 'SKIN MUDA', 'keterangan' => 'SKIN MUDA'],
                ['kode' => 'WRN.560', 'nama' => 'SKIN TUA', 'keterangan' => 'SKIN TUA'],
                ['kode' => 'WRN.561', 'nama' => 'C. KOPI', 'keterangan' => 'C. KOPI'],
                ['kode' => 'WRN.562', 'nama' => 'L. PURPLE', 'keterangan' => 'L. PURPLE'],
                ['kode' => 'WRN.563', 'nama' => 'P. PURPLE', 'keterangan' => 'P. PURPLE'],
                ['kode' => 'WRN.564', 'nama' => 'VIOLET', 'keterangan' => 'VIOLET'],
                ['kode' => 'WRN.565', 'nama' => 'BURGUNDI', 'keterangan' => 'BURGUNDI'],
                ['kode' => 'WRN.566', 'nama' => 'MERAH HATI', 'keterangan' => 'MERAH HATI'],
                ['kode' => 'WRN.567', 'nama' => 'M. BATA', 'keterangan' => 'M. BATA'],
                ['kode' => 'WRN.568', 'nama' => 'M. CABE', 'keterangan' => 'M. CABE'],
                ['kode' => 'WRN.569', 'nama' => 'FUCHSIA', 'keterangan' => 'FUCHSIA'],
                ['kode' => 'WRN.570', 'nama' => 'KUNING D', 'keterangan' => 'KUNING D'],
                ['kode' => 'WRN.571', 'nama' => 'MERAH CABE D.', 'keterangan' => 'MERAH CABE D.'],
                ['kode' => 'WRN.572', 'nama' => 'SKIN D.', 'keterangan' => 'SKIN D.'],
                ['kode' => 'WRN.573', 'nama' => 'ROYAL BLUE D.', 'keterangan' => 'ROYAL BLUE D.'],
                ['kode' => 'WRN.574', 'nama' => 'NAVY BLUE D.', 'keterangan' => 'NAVY BLUE D.'],
                ['kode' => 'WRN.575', 'nama' => 'PUTIH D.', 'keterangan' => 'PUTIH D.'],
                ['kode' => 'WRN.576', 'nama' => 'HITAM D.', 'keterangan' => 'HITAM D.'],
                ['kode' => 'WRN.577', 'nama' => 'PINK D.', 'keterangan' => 'PINK D.'],
                ['kode' => 'WRN.578', 'nama' => 'PINK', 'keterangan' => 'PINK'],
                ['kode' => 'WRN.579', 'nama' => 'PINK MUDA', 'keterangan' => 'PINK MUDA'],
                ['kode' => 'WRN.580', 'nama' => 'PINK TUA', 'keterangan' => 'PINK TUA'],
                ['kode' => 'WRN.581', 'nama' => 'FUSHSIA', 'keterangan' => 'FUSHSIA'],
                ['kode' => 'WRN.582', 'nama' => 'R BLUE', 'keterangan' => 'R BLUE'],
                ['kode' => 'WRN.583', 'nama' => 'BIRU BCA', 'keterangan' => 'BIRU BCA'],
                ['kode' => 'WRN.584', 'nama' => 'BABY BLUE', 'keterangan' => 'BABY BLUE'],
                ['kode' => 'WRN.585', 'nama' => 'B. AZUE', 'keterangan' => 'B. AZUE'],
                ['kode' => 'WRN.586', 'nama' => 'TURQUISH', 'keterangan' => 'TURQUISH'],
                ['kode' => 'WRN.587', 'nama' => 'TOSCA TUA', 'keterangan' => 'TOSCA TUA'],
                ['kode' => 'WRN.588', 'nama' => 'KUNING', 'keterangan' => 'KUNING'],
                ['kode' => 'WRN.589', 'nama' => 'O. NEON', 'keterangan' => 'O. NEON'],
                ['kode' => 'WRN.590', 'nama' => 'O. HERME', 'keterangan' => 'O. HERME'],
                ['kode' => 'WRN.591', 'nama' => 'K. MANGGA', 'keterangan' => 'K. MANGGA'],
                ['kode' => 'WRN.592', 'nama' => 'MAROON 1', 'keterangan' => 'MAROON 1'],
                ['kode' => 'WRN.593', 'nama' => 'COKLAT TUA 2', 'keterangan' => 'COKLAT TUA 2'],
                ['kode' => 'WRN.594', 'nama' => 'MOCCA 3', 'keterangan' => 'MOCCA 3'],
                ['kode' => 'WRN.595', 'nama' => 'HITAM 4', 'keterangan' => 'HITAM 4'],
                ['kode' => 'WRN.596', 'nama' => 'COKLAT 6', 'keterangan' => 'COKLAT 6'],
                ['kode' => 'WRN.597', 'nama' => 'NAVY 8', 'keterangan' => 'NAVY 8'],
                ['kode' => 'WRN.598', 'nama' => 'ABU SEDANG 9', 'keterangan' => 'ABU SEDANG 9'],
                ['kode' => 'WRN.599', 'nama' => 'ROSE 13', 'keterangan' => 'ROSE 13'],
                ['kode' => 'WRN.600', 'nama' => 'PUTIH 33', 'keterangan' => 'PUTIH 33'],
                ['kode' => 'WRN.601', 'nama' => 'MAUVE 39', 'keterangan' => 'MAUVE 39'],
                ['kode' => 'WRN.602', 'nama' => 'OLIVE 47', 'keterangan' => 'OLIVE 47'],
                ['kode' => 'WRN.603', 'nama' => 'ABU MUDA 77', 'keterangan' => 'ABU MUDA 77'],
                ['kode' => 'WRN.604', 'nama' => 'ORANGE BATA 81', 'keterangan' => 'ORANGE BATA 81'],
                ['kode' => 'WRN.605', 'nama' => 'BLUE REFF 98', 'keterangan' => 'BLUE REFF 98'],
                ['kode' => 'WRN.606', 'nama' => 'SAGE GREEN 102', 'keterangan' => 'SAGE GREEN 102'],
                ['kode' => 'WRN.607', 'nama' => 'DUSTY GREEN 110', 'keterangan' => 'DUSTY GREEN 110'],
                ['kode' => 'WRN.608', 'nama' => 'DARK MUSTARD 112', 'keterangan' => 'DARK MUSTARD 112'],
                ['kode' => 'WRN.609', 'nama' => 'MAGENTA 113', 'keterangan' => 'MAGENTA 113'],
                ['kode' => 'WRN.610', 'nama' => 'BIRU SEDANG 08', 'keterangan' => 'BIRU SEDANG 08'],
                ['kode' => 'WRN.611', 'nama' => 'UNGU MUDA 14', 'keterangan' => 'UNGU MUDA 14'],
                ['kode' => 'WRN.612', 'nama' => 'PINK 15', 'keterangan' => 'PINK 15'],
                ['kode' => 'WRN.613', 'nama' => 'DUSTY GREEN 06', 'keterangan' => 'DUSTY GREEN 06'],
                ['kode' => 'WRN.614', 'nama' => 'CREAM 17', 'keterangan' => 'CREAM 17'],
                ['kode' => 'WRN.615', 'nama' => 'COKLAT 16', 'keterangan' => 'COKLAT 16'],
                ['kode' => 'WRN.616', 'nama' => 'ROSE 22', 'keterangan' => 'ROSE 22'],
                ['kode' => 'WRN.617', 'nama' => 'DUSTY PINK 13', 'keterangan' => 'DUSTY PINK 13'],
                ['kode' => 'WRN.618', 'nama' => 'MOCCA 18', 'keterangan' => 'MOCCA 18'],
                ['kode' => 'WRN.619', 'nama' => 'LIGHT GREY 09', 'keterangan' => 'LIGHT GREY 09'],
                ['kode' => 'WRN.620', 'nama' => 'ABU TUA 11', 'keterangan' => 'ABU TUA 11'],
                ['kode' => 'WRN.621', 'nama' => 'MILO 10', 'keterangan' => 'MILO 10'],
                ['kode' => 'WRN.622', 'nama' => 'COKLAT ABU 21', 'keterangan' => 'COKLAT ABU 21'],
                ['kode' => 'WRN.623', 'nama' => 'DUSTY PINK 12', 'keterangan' => 'DUSTY PINK 12'],
                ['kode' => 'WRN.624', 'nama' => 'PUTIH 01', 'keterangan' => 'PUTIH 01'],
                ['kode' => 'WRN.625', 'nama' => 'LATTE 19', 'keterangan' => 'LATTE 19'],
                ['kode' => 'WRN.626', 'nama' => 'BURGUNDY 20', 'keterangan' => 'BURGUNDY 20'],
                ['kode' => 'WRN.627', 'nama' => 'HITAM 02', 'keterangan' => 'HITAM 02'],
                ['kode' => 'WRN.628', 'nama' => '-', 'keterangan' => '-'],
                ['kode' => 'WRN.629', 'nama' => '--', 'keterangan' => '--'],
                ['kode' => 'WRN.630', 'nama' => '1  PUTIH ALL', 'keterangan' => '1  PUTIH ALL'],
                ['kode' => 'WRN.631', 'nama' => '2  BROKEN WHITE ALL', 'keterangan' => '2  BROKEN WHITE ALL'],
                ['kode' => 'WRN.632', 'nama' => 'ABU MUDA ALL', 'keterangan' => 'ABU MUDA ALL'],
                ['kode' => 'WRN.633', 'nama' => '1 PUTIH ALL', 'keterangan' => '1 PUTIH ALL']
            ],
            ['kode'],
            ['nama', 'keterangan']
        );
    }
}
